#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

# this assumes python installed via homebrew

if chk_osx
then
  sudo ln -s /usr/bin/pip3 /usr/bin/pip
  sudo ln -s /usr/bin/python3 /usr/bin/python
fi

if chk_linux
then
  sudo ln -s /home/linuxbrew/.linuxbrew/bin/pip3 /usr/bin/pip
  sudo ln -s /home/linuxbrew/.linuxbrew/bin/python3 /usr/bin/python
fi
