#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

if chk_linux
then
  https://github.com/99designs/aws-vault/releases/download/v6.3.1/aws-vault-linux-amd64
fi

if chk_osx
then
  brew install --cask aws-vault
fi
