#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

if chk_linux
then
  sudo sudo apt-get -qq update && sudo sudo apt-get -qq install -y \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

  curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  sudo sudo apt-get -qq update && sudo sudo apt-get -qq install -y docker-ce docker-ce-cli containerd.io

  sudo usermod -aG docker "$(whoami)"
fi

if chk_osx
then
  brew install --cask docker
fi
