#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

if chk_linux
then
  wget --quiet https://prerelease.keybase.io/keybase_amd64.deb
  sudo dpkg -i keybase_amd64.deb
  rm keybase_amd64.deb

  sudo sudo apt-get -qq install -y --fix-broken
fi

if chk_osx
then
  brew install --cask keybase
fi
