#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

if chk_linux
then
  sudo sudo apt-get -qq update && sudo sudo apt-get -qq install -y virtualbox
fi

if chk_osx
then
  brew install --cask virtualbox
  brew install --cask virtualbox-extension-pack
fi
