#!/usr/bin/env bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

# shellcheck disable=SC1090
source "$DIR/../lib/sh"

if chk_linux
then
  wget -qO- https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo apt-key add -
  sudo add-apt-repository "deb [arch=amd64] https://packages.microsoft.com/repos/code stable main"
  sudo sudo apt-get -qq update && sudo sudo apt-get -qq install -y code # or code-insiders
fi

if chk_osx
then
  brew install --cask visual-studio-code
fi
