#!/usr/bin/env bash

export XDG_CONFIG_HOME="${XDG_CONFIG_HOME:-"$HOME/.config"}"

#
# usage:
#     xdg_dir "asdf"

xdg_dir() {
  local dir="$1"

  # shellcheck disable=SC2005
  echo "$([ -z "${XDG_CONFIG_HOME-}" ] && printf %s "${HOME}/.${dir}" || printf %s "${XDG_CONFIG_HOME}/${dir}")"
}

ASDF_DIR="$(xdg_dir "asdf")"
export ASDF_DIR
export ASDF_DATA_DIR="${HOME}/.asdf"

# shellcheck disable=SC1090
source "${ASDF_DIR}/asdf.sh"

# chk_debian returns true if this OS is Debian Linux
# usage:
#     chk_debian && echo_green "this is Debian Linux"
chk_debian() {
  uname -a | grep "Debian" &> /dev/null
}

# chk_linux returns true if this OS is Linux
# usage:
#     chk_linux && echo_green "this is Linux"
chk_linux() {
  uname -a | grep "Linux" &> /dev/null
}

# chk_osx returns true if this OS is Darwin
# usage:
#     chk_osx && echo_green "this is Mac OS"
chk_osx() {
  uname -a | grep "Darwin" &> /dev/null
}

# chk_ubuntu returns true if this OS is Ubuntu Linux
# usage:
#     chk_ubuntu && echo_green "this is Ubuntu Linux"
chk_ubuntu() {
  uname -a | grep "Ubuntu" &> /dev/null
}

# chk_empty returns true if a given value is empty
# usage:
#     chk_empty "xx" || echo_red "not empty"
chk_empty() {
  local var="$1"
  [ -z "$var" ]
}

# install asdf plugin and latest version
# USAGE:
#   pkg_install_asdf pluginname pluginrepo
pkg_install_asdf() {
  local pkg="${1}"
  local repo="${2}"
  asdf plugin-add "$pkg" "$repo"
  asdf install "$pkg" "$(asdf list-all "$pkg" | grep -v a | grep -v e | grep -v c | grep -v y | tail -1 | xargs)"
  asdf global "$pkg" "$(asdf list "$pkg" | tail -1 | xargs)"
}
